arm/ai-ml-emulation-layer-for-vulkan

graph/graph_layer.cpp
Change-Id: I99810a73615e880397feafae0b31046b302ac7aa
=> Small whitespace fix

docs/source/index.rst, docs/source/puml.rst
Change-Id: I134f51a7c0f3a7a8c27cbef59aa735d5f62b68ae
=> Remove puml diagrams from docs

graph/tosa/rfft2d.comp
Change-Id: I86e5e51362afe487c8ffa6a6d1dc3119c2ed9d53
=> Fix failing TOSA CTS rfft2d tests

CMakeLists.txt, README.md, docs/source/cloning.rst, docs/source/index.rst
Consistent capitalization
Added component specific doc build variable
and cache clearing
Change-Id: I73a6f9428728fe4b652e4c90f598480c08e9099e
=> Update documentation and build process

README.md
Change-Id: I80313d280abd31cd5be2ac24ef130c54f78b51f1
=> Fix doc linking issue

graph/graph_layer.cpp, tensor/tensor_layer.cpp
Fix the issue of invalid objects
Change-Id: I796a780122cf01d527ddfb722ba4cc94a7553c0a
=> Overload `vkSetDebugUtilsObjectNameEXT` in Graph and Tensor Layer

tensor/tensor_layer.cpp
Change-Id: I99810a73615e880397feafae0b31046b302ac7ad
=> Add support for sub-allocations in memory aliasing

graph/compute.cpp, graph/tosa/elementwise_unary.comp
Change-Id: Ic3aff3d8605bf5cd3f333872b3c5d95c92827c72
=> Add sign check for log operator

graph/graph_layer.cpp, tensor/tensor_layer.cpp
Change-Id: I01d8cc6871a2031fd7a96cfdd2c4cbf521e311f1
=> Improve thread safety and resource deallocation

graph/spirv_pass.cpp, graph/spirv_pass.hpp
Change-Id: I7d40bfc3cdd551bd3f7fcae53235194076846d8f
=> Rename TensorEXT to TensorARM

tensor/tensor_layer.cpp
Use local handle variable to simplify code
Change-Id: I86dcd6eab4fd2ae738a500e866f552e546171dc6
=> nullptr check and remove redundant scopes

graph/graph_layer.cpp
Change-Id: Ie16b1fa69d936f6afd855187d9b04dc93c2ab52f
=> Add warning when trying to use pipeline caching

docs/source/cloning.rst
Change-Id: Ie30d892f076e31f73d1229e21a45a4c75001cd3a
=> Add url to manifest

tensor/tensor_ext.cpp
Make variables const to signal intent.
Change-Id: Ib465e7e4b1363ed4bcbb48ead6cfa86c1a225413
=> Add flag to descriptor pool create info

tests/vulkan.cpp, utilities/include/mlel/tensor.hpp, utilities/tensor.cpp
Make sure that buffer info have the correct usage flag.
Change-Id: I219dfc053f92b2f700a89639853ba46c90096653
=> Fix unit test for tensor copy

docs/docs.cmake, docs/source/conf.py
Change-Id: I27d1db5476fd3bebd7ba6cdc37ec13c81fd9d081
=> Suppress unwanted doc build warnings and fail on new warnings

tooling-requirements.txt
Documentation dependencies and other tools.
=> Add missing tooling-requirements.txt

graph/tosa/CMakeLists.txt
Change-Id: I35feb433ebe899ca0812ee21b29b91cb9d6e8a6e
=> Fix POSIX like generators to build on Windows

tests/vulkan.cpp
To prevent inclusion of vulkan beta headers
Change-Id: Ieee46f0fbbe0323a8ab9c38ea444c5acfbac24b7
=> Use String version of portability subset extension

common/include/mlel/utils.hpp, common/utils.cpp
Change-Id: I72aaa8ef2e1db8aff52267805afe72be993425ba
=> Cleanup unused functions

graph/tosa/CMakeLists.txt
Change-Id: I2e6aaad488d9f74161882ed8f443fbcb95cfbe6b
=> Modify custom cmake commands to fix windows cmd length issues

scripts/build.py
Change-Id: I5c42c04b1256f3fbc4d15f4ea45b18ac87729ac5
=> Add --package-source option into build script

tooling-requirements.txt
Input from SBOM and docker build log
Change-Id: I07fdc0e2ac4e1488eab16e4f880b0e0b8c5bc047
=> Fix requirement versions

graph/graph_layer.cpp
Change-Id: I38265b782501ed274e220becf2c19b25166b8372
=> Advertise supported features in tensor and graph layers

scripts/build.py
Change-Id: I6db75b24a811ee26269304882ac15f882669d241
=> Add linux-clang target into the build script

.pre-commit-config.yaml
Change-Id: I3c435f436eeba65e9c891a69ac8f25902fbb726e
=> Removing prettier pre-commit hook

common/include/mlel/vulkan_layer.hpp
Change-Id: I3f13d28f92ff7797879980b00d39f058a4e1f21a
=> Add constexpr size check to avoid dead code

graph/graph_layer.cpp, tests/vulkan.cpp
Change-Id: I35d0a28188c12a3bfeb98949327e8c9d63cc97e2
=> Provide feedback to VkPipelineCreationFeedbackCreateInfo

.reuse/dep5, CMakeLists.txt, pip_package/setup.py
Change-Id: I525be72673a84aa8fb252d1f61daa132a6d4e526
=> Align package names to repo names

scripts/build.py
Change-Id: Ia961cdc2bfe8a8be02a92fe18bbce4b9158e7231
=> Fix: build script wasn't handling linux-clang properly

graph/graph_layer.cpp
and vkGetDataGraphPipelineAvailablePropertiesARM
Change-Id: I6bc798c5bc0d3171940e6f59c3de0bc4b88f7457
=> Implement vkGetDataGraphPipelinePropertiesARM

README.md, RELEASE_NOTES.md, docs/source/usage.rst
=> Add platform support info to the release notes

common/include/mlel/utils.hpp, common/include/mlel/vulkan_layer.hpp, graph/graph_layer.cpp, graph/layer.d/VkLayer_Graph.json.in, tests/vulkan.cpp, utilities/include/mlel/exception.hpp
Sort functions alphabetically.
Add basic unit tests.
Remove anonymous namespaces from header files.
Change-Id: I431508c013a7deff0ecd047afec42c05518545f0
=> Update layer json

scripts/build.py
Change-Id: I0211115d281a94dc1cfe56dc4b00c6c69dc16040
=> Add Darwin to platforms supported in build script

scripts/build.py
Change-Id: Idadb35eb0c8ec70b2f37b5f47a2aa19e11402fe9
=> Minor change
